server:
  port: 8080
  servlet:
    context-path: /consumer

spring:
  application:
    name: demo-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

swagger:
  enabled: true

